platform :ios, '13.0'

target 'GukouFitness' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GukouFitness 

pod 'CLTypingLabel', '~> 0.4.0'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'

end
